version: '3.8'

services:
  telegram_volleyball_bot:
    image: philippkrytoi/telegram-volleyball-bot:${VERSION}
    restart: unless-stopped
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      ADMIN_CHAT_ID: ${ADMIN_CHAT_ID}
    networks:
      - telegram_volleyball_bot_network

networks:
  telegram_volleyball_bot_network:
