version: '3.8'

services:
  telegram-bot:
    image: telegram-volleyball-bot:latest
    container_name: telegram-volleyball-bot
    restart: unless-stopped
    environment:
      TELEGRAM_BOT_TOKEN: "8100778277:AAFdh8ZubXRN41ZR-HABXxSttckPNT54grU"
      ADMIN_CHAT_ID: "@VolleyUsmBot"
    # Если бот пишет логи в файл, можно подключить том:
    volumes:
      - ./logs:/app/logs
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
